version: "3.8"
services:
  db:
    build: ./db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGPORT: 5433
    ports:
      - 5433:5433
    expose:
      - 5433
  pythonapp:
    build: ./python
    restart: unless-stopped
    volumes:
      - ./volumes/dados-publicos:/app/dados-publicos
      - ./volumes/dados-publicos-zip:/app/dados-publicos-zip
    environment:
      - DATABASE_IP=db
      - DATABASE_PORT=5433
      - DATABASE_NAME=cnpj
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    command: tail -f /dev/null